baseURL = "/"
languageCode = "en-us"
title = "Organized Vancouver"
theme = "ananke"
description = "Organized Vancouver is a professional organizing company based in Vancouver, BC, servicing the Lower Mainland. We help busy professionals at home and in their work. We aim to create organization systems to help you get control of your home and office - and your schedule!"
